# -*- coding: utf-8 -*-
"""lab_TSdiff.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10CYpCqP5su6kA3AiaNwpXiHAn6pSuGg0
"""

from google.colab import drive
drive.mount('/content/drive')

cd drive/MyDrive/Datalab/practice

import os
import shutil
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torch.nn as nn
import torch.optim as optim

!pip install pypots

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/amazon-science/unconditional-time-series-diffusion.git
# %cd unconditional-time-series-diffusion

# 1. 기존에 설치된 꼬인 패키지들 정리 및 최신 안정화 버전 설치
!pip install --upgrade pydantic gluonts pytorch-lightning typing-extensions s3fs

import os

# GluonTS의 에러 지점을 찾아 강제로 수정
target_file = "/usr/local/lib/python3.12/dist-packages/gluonts/exceptions.py"

if os.path.exists(target_file):
    with open(target_file, "r") as f:
        content = f.read()

    # 에러를 일으키는 구형 import 문을 최신 pydantic v2 대응 코드로 교체
    old_line = "from pydantic.error_wrappers import ValidationError, display_errors"
    new_line = "try:\n    from pydantic.v1.error_wrappers import ValidationError, display_errors\nexcept:\n    from pydantic.error_wrappers import ValidationError"

    if old_line in content:
        new_content = content.replace(old_line, new_line)
        with open(target_file, "w") as f:
            f.write(new_content)
        print("✅ GluonTS 소스 코드 수정 성공!")
    else:
        print("ℹ️ 이미 수정되어 있거나 코드가 다릅니다.")
else:
    print("❌ 파일을 찾을 수 없습니다. 설치를 확인하세요.")

!pip install --upgrade pydantic gluonts pytorch-lightning typing-extensions

!pip install lightning

# 꼬인 버전들을 무시하고 가장 안정적인 조합으로 재설치
!pip install "pydantic<2.0.0" gluonts==0.13.2 pytorch-lightning==1.9.5 lightning s3fs

import os
target_file = "/usr/local/lib/python3.12/dist-packages/gluonts/exceptions.py"

if os.path.exists(target_file):
    with open(target_file, "r") as f:
        content = f.read()
    old_line = "from pydantic.error_wrappers import ValidationError, display_errors"
    new_line = "try:\n    from pydantic.v1.error_wrappers import ValidationError, display_errors\nexcept:\n    from pydantic.error_wrappers import ValidationError"
    if old_line in content:
        with open(target_file, "w") as f:
            f.write(content.replace(old_line, new_line))
        print("✅ GluonTS 소스 코드 수정 완료!")
    else:
        print("✅ 이미 수정되어 있습니다.")

import os
path = "/content/drive/MyDrive/data/tsdiff_input/worldbank_custom.jsonl"
if os.path.exists(path):
    print("✅ 데이터 파일이 정상적으로 존재합니다.")
    with open(path, 'r') as f:
        print(f"✅ 첫 줄 데이터 확인: {f.readline()[:50]}...")
else:
    print("❌ 파일 경로가 잘못되었습니다. 경로를 다시 확인하세요!")

!pip install "gluonts[torch]"

import os
import sys
import typing
from typing import ForwardRef

# 1. 환경 패치 (필수)
def patched_evaluate(self, globalns, localns, type_params=None, recursive_guard=None):
    try: return self._evaluate(globalns, localns, type_params, recursive_guard=recursive_guard)
    except: return self._evaluate(globalns, localns)
ForwardRef._evaluate = patched_evaluate

from gluonts.torch.modules.loss import DistributionLoss

try:
    import gluonts.torch.scaler as scaler
    sys.modules['gluonts.torch.modules.scaler'] = scaler
    print("✅ Scaler 경로 보정 완료")
except ImportError:
    print("⚠️ Scaler를 찾을 수 없습니다. GluonTS 설치를 확인하세요.")

# Commented out IPython magic to ensure Python compatibility.

# 2. 경로 설정
root_dir = "/content/drive/MyDrive/Datalab/practice/unconditional-time-series-diffusion"
sys.path.append(os.path.join(root_dir, "src"))
os.environ['PYTHONPATH'] = f"{os.environ.get('PYTHONPATH', '')}:{root_dir}/src"
# %cd {root_dir}

!pip install gluonts==0.14.4

!python bin/train_model.py \
    --dataset /content/drive/MyDrive/data/tsdiff_input/worldbank_custom.jsonl \
    --config configs/base.yaml \
    --freq 1Y \
    --prediction_length 5 \
    --context_length 26 \
    --device cuda:0 \
    --batch_size 4 \
    --num_workers 0 \
    --limit_train_batches 10 \
    --limit_val_batches 5 \
    --max_epochs 1

import sys
import os
import typing
from typing import ForwardRef
root_dir = "/content/drive/MyDrive/Datalab/practice/unconditional-time-series-diffusion"
os.chdir(root_dir)

# 2. 파이썬이 src 폴더를 찾을 수 있도록 환경 변수 설정 (Import 에러 해결)
os.environ['PYTHONPATH'] = f"{os.environ.get('PYTHONPATH', '')}:{root_dir}/src"
# 1. ForwardRef 에러 (recursive_guard) 해결을 위한 패치
def patched_evaluate(self, globalns, localns, type_params=None, recursive_guard=None):
    # 인자가 어떻게 들어오든 내부의 진짜 evaluate에 맞춰서 전달합니다.
    try:
        return self._evaluate(globalns, localns, type_params, recursive_guard=recursive_guard)
    except TypeError:
        return self._evaluate(globalns, localns)

ForwardRef._evaluate = patched_evaluate

# 2. Pydantic v1/v2 ImportError 해결을 위한 패치
try:
    # 최신 pydantic 내부에 v1 호환 모듈이 있는지 확인
    import pydantic.v1.error_wrappers as wrappers
    sys.modules['pydantic.error_wrappers'] = wrappers
    print("✅ Pydantic 호환성 연결 완료")
except ImportError:
    print("⚠️ Pydantic v1을 찾을 수 없으나 최신 버전으로 진행합니다.")

# 3. 작업 경로 이동 및 학습 스크립트 실행
os.chdir("/content/drive/MyDrive/Datalab/practice/unconditional-time-series-diffusion")
print(f"📂 현재 경로: {os.getcwd()}")

# 4. 학습 명령어 실행
!python bin/train_model.py \
    --dataset /content/drive/MyDrive/data/tsdiff_input/worldbank_custom.jsonl \
    --config configs/base.yaml \
    --freq 1Y \
    --prediction_length 5 \
    --context_length 26 \
    --device cuda:0

# 4. 학습 명령어 실행
!python bin/train_model.py \
    --dataset /content/drive/MyDrive/data/tsdiff_input/worldbank_custom.jsonl \
    --config configs/base.yaml \
    --freq 1Y \
    --prediction_length 5 \
    --context_length 26 \
    --device cuda:0

import json
import numpy as np
from pathlib import Path

# 1. 아까 저장했던 NPZ 파일 불러오기 (경로를 확인하세요)
# 보간 결과가 들어있는 npz 파일을 로드합니다.
npz_path = "/content/drive/MyDrive/Datalab/data/CSDI_tens.npz" # 또는 SAITS_tens.npz
data_loaded = np.load(npz_path, allow_pickle=True)

# 2. 스케일링 된 텐서 데이터 추출
# 'data' 키에 저장된 값이 모델 학습용 스케일링 데이터입니다.
train_set = data_loaded['data'] # Shape: (Samples, Steps, Features)

# 만약 데이터가 4차원(예: [214, 1, 31, 12])이라면 3차원으로 축소
if train_set.ndim == 4:
    train_set = np.squeeze(train_set)

print(f"✅ 학습용 텐서 로드 완료: {train_set.shape}")

# 3. JSONL 변환 및 저장
output_dir = Path("/content/drive/MyDrive/data/tsdiff_input")
output_dir.mkdir(parents=True, exist_ok=True)
jsonl_path = output_dir / "worldbank_custom.jsonl"

start_date = "1990-01-01"

with open(jsonl_path, "w", encoding="utf-8") as f:
    for i in range(train_set.shape[0]):
        # target_data는 (Features, Steps) 구조여야 함 -> .T
        target_data = train_set[i].T.tolist()

        entry = {
            "start": start_date,
            "target": target_data
        }
        f.write(json.dumps(entry) + "\n")

print(f"🚀 TSDiff 입력용 JSONL 생성 완료! (스케일링 데이터 사용)")

import sys
import typing
from typing import ForwardRef

# 1. Python 3.12용 ForwardRef 완전 패치
# 인자의 개수나 이름을 따지지 않고 원래의 _evaluate로 토스하되,
# 에러가 나면 구형 방식으로 재시도합니다.
def universal_patch(self, *args, **kwargs):
    try:
        # 최신 방식 (인자 4개 이상) 시도
        return self._original_evaluate(self, *args, **kwargs)
    except Exception:
        # 구형 방식 (globalns, localns만 전달) 시도
        globalns = args[0] if len(args) > 0 else kwargs.get('globalns')
        localns = args[1] if len(args) > 1 else kwargs.get('localns')
        return self._original_evaluate(self, globalns, localns)

if not hasattr(ForwardRef, '_original_evaluate'):
    ForwardRef._original_evaluate = ForwardRef._evaluate
    ForwardRef._evaluate = universal_patch

# 2. Pydantic v1/v2 호환성 강제 연결
try:
    import pydantic.v1.error_wrappers as wrappers
    sys.modules['pydantic.error_wrappers'] = wrappers
    print("✅ Pydantic/Typing 패치 완료 (Python 3.12 대응)")
except ImportError:
    # 만약 pydantic.v1이 없다면 최신 pydantic에서 직접 시도
    try:
        import pydantic.error_wrappers as wrappers
        print("✅ Pydantic 최신 모듈 연결 완료")
    except ImportError:
        print("⚠️ Pydantic 모듈 구조가 예상과 다릅니다.")

print("🚀 이제 아래 셀에서 학습을 시작하세요!")

# !!! when I want to use my dataset for training
# https://github.com/amazon-science/unconditional-time-series-diffusion/issues/7
import logging
import argparse
from pathlib import Path

import yaml
import torch
from tqdm.auto import tqdm
import pytorch_lightning as pl
from pytorch_lightning.callbacks import ModelCheckpoint, RichProgressBar
import typing
from typing import ForwardRef

# Python 3.10+ 에서 발생하는 ForwardRef._evaluate 에러를 방지하기 위한 원숭이 패치(Monkey Patch)
if not hasattr(ForwardRef, "recursive_guard"):
    def _evaluate_patch(self, globalns, localns, recursive_guard=set()):
        return self._evaluate(globalns, localns)
    ForwardRef._evaluate = _evaluate_patch

from gluonts.dataset.loader import TrainDataLoader
from gluonts.dataset.split import OffsetSplitter
from gluonts.itertools import Cached
from gluonts.torch.batchify import batchify
from gluonts.evaluation import make_evaluation_predictions, Evaluator
from gluonts.dataset.field_names import FieldName

import uncond_ts_diff.configs as diffusion_configs
from uncond_ts_diff.dataset import get_gts_dataset
from uncond_ts_diff.model.callback import EvaluateCallback
from uncond_ts_diff.model import TSDiff
from uncond_ts_diff.sampler import DDPMGuidance, DDIMGuidance
from uncond_ts_diff.utils import (
    create_transforms,
    create_splitter,
    add_config_to_argparser,
    filter_metrics,
    MaskInput,
)

guidance_map = {"ddpm": DDPMGuidance, "ddim": DDIMGuidance}



def get_custom_dataset(
    jsonl_path: Path,
    freq: str,
    prediction_length: int,
    split_offset: int = None,
):
    """Creates a custom GluonTS dataset from a JSONLines file and
    give parameters.

    Parameters
    ----------
    jsonl_path
        Path to a JSONLines file with time series
    freq
        Frequency in pandas format
        (e.g., `H` for hourly, `D` for daily)
    prediction_length
        Prediction length
    split_offset, optional
        Offset to split data into train and test sets, by default None

    Returns
    -------
        A gluonts dataset
    """
    if split_offset is None:
        split_offset = -prediction_length

    metadata = MetaData(freq=freq, prediction_length=prediction_length)
    test_ts = FileDataset(jsonl_path, freq)
    train_ts, _ = split(test_ts, offset=split_offset)
    dataset = TrainDatasets(metadata=metadata, train=train_ts, test=test_ts)
    return dataset

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/unconditional-time-series-diffusion

# TSDiff 학습 스크립트 실행
!python bin/train_model.py \
    --jsonl_path /content/drive/MyDrive/data/tsdiff_input/worldbank_custom.jsonl \
    --freq 1Y \
    --prediction_length 5 \
    --context_length 26 \
    --input_size 12 \
    --n_layers 4 \
    --diff_steps 100 \
    --epochs 50 \
    --batch_size 32 \
    --device cuda

